### ISSUE TITLE
RTYI: Thesis on reverse engineering .lyr files

### ISSUE THREAD

**Issue by keithamoss** [nyalldawson/esri_style_specs#1]
Thought you might be interested in this thesis from a Stockholm University student.

[Closed to Open Source GIS - First Steps in Reverse Engineering ESRI’s Layer Definition File Format](https://su.diva-portal.org/smash/get/diva2:1086367/FULLTEXT01.pdf)

I've only skimmed it so far, so not sure actually how useful it would be to your project here :)

**Comment by nyalldawson** [comment]
Thanks Keith - that looks very useful! I've sent an email to Ola and hopefully we can solve a bit more of this problem...
